title: Manuale GeoTecSUE
description: >
  Guida operativa per professionisti all'utilizzo del portale GeoTecSUE.

url: "https://andrea-siscom.github.io"
baseurl: "/GeoTecSUE-Manuale"

remote_theme: klaudiosinani/re

plugins:
  - jekyll-remote-theme

locale: it-IT
timezone: Europe/Rome
